name: nginx server installation
on: push
jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: updating the repository
        run: sudo apt update -y
  installation:
    needs: build
    runs-on: self-hosted
    steps:
      - name: installign nginx
        run: sudo apt install nginx -y
      - name: enabling firewall
        run: sudo ufw allow 'Nginx HTTP'
  updating_web_page:
    needs: installation
    runs-on: self-hosted
    steps:
      run: sudo cp index.nginx-debian.html >/var/www/html/index.nginx-debian.html
